dependencies {
    testImplementation project(':common')
    testImplementation project(':api')

    testImplementation "org.testcontainers:junit-jupiter:$testcontainersVersion"
    testImplementation "org.testcontainers:postgresql:$testcontainersVersion"
    testImplementation "org.postgresql:postgresql:42.7.2"
}
