# Тестируемое приложение
base.url=https://app.todoist.com
api.url=https://api.todoist.com
api.version=/api/v1

# Web (Selenide)
browser=CHROME
browser.size=1920x1080
is.remote=false
web.timeout.ms=15000
web.headless=true
web.page.load.strategy=eager
# remote.url=
# browser.version=

# API-моки (WireMock)
mock.test.token=test_local_token_secure_123
mock.invalid.token=invalid_token_xyz_999

# Mobile: приложение и Appium
# Значение по умолчанию; Gradle-задачи android / androidLocal переопределяют его через -D
mobile.provider=local
app.package=com.todoist
app.activity=com.todoist.activity.HomeActivity
appium.local.url=http://127.0.0.1:4723
device.timezone=Europe/Moscow
local.apk.path=src/test/resources/apps/todoist.apk

# Mobile: BrowserStack
bs.device=Google Pixel 7
bs.os.version=13.0
bs.timezone=Moscow
bs.project.name=Todoist Mobile Automation
bs.build.name=Diploma_Mobile_Build
