Project=Todoist QA Automation
Application.Under.Test=Todoist
Web.Base.Url=https://app.todoist.com
API.Base.Url=https://api.todoist.com
API.Version=/api/v1
Test.Layer.API=REST Assured + WireMock
Test.Layer.Web=Selenide
Test.Layer.Mobile=Appium
Test.Layer.DB=Testcontainers (PostgreSQL 16)
Web.Browser=Chrome
Mobile.Platform=Android (UiAutomator2)
Language=Java 17
Test.Framework=JUnit 5
Reporting=Allure 2.27.0
Build.Tool=Gradle
