dependencies {
    testImplementation project(':common')
    testImplementation project(':api')

    testImplementation platform('org.seleniumhq.selenium:selenium-bom:4.22.0')
    testImplementation 'org.seleniumhq.selenium:selenium-java'
    testImplementation "com.codeborne:selenide:$selenideVersion"
    testImplementation "io.qameta.allure:allure-selenide:$allureVersion"
}

test {
    systemProperty 'junit.jupiter.execution.parallel.enabled', 'false'
    systemProperty 'junit.jupiter.execution.parallel.mode.default', 'concurrent'
    systemProperty 'junit.jupiter.execution.parallel.mode.classes.default', 'concurrent'
    systemProperty 'junit.jupiter.execution.parallel.config.strategy', 'fixed'
    systemProperty 'junit.jupiter.execution.parallel.config.fixed.parallelism', '2'
    systemProperty 'junit.jupiter.execution.parallel.config.fixed.max-pool-size', '2'
}

task saveSession(type: JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'todoist.helpers.SaveSessionTool'
}
